import {
  Bike,
  BicepsFlexed,
  CalendarDays,
  CircleCheck,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  CirclePlus,
  Clock3,
  Dumbbell,
  Droplet,
  Flame,
  Flower2,
  Footprints,
  Goal,
  CircleHelp,
  MoonStar,
  Mountain,
  Music2,
  Pencil,
  PersonStanding,
  SportShoe,
  Stethoscope,
  Trash2,
  TriangleAlert,
  Utensils,
  Scale,
  Volleyball,
  Waves,
  Wheat,
  X,
  ChartNoAxesCombined,
  ChevronDown,
  House,
  LogOut,
  Lightbulb,
  Menu,
  MessageCircleHeart,
  Moon,
  TrendingUp,
  Coffee,
  Cookie,
  Sandwich,
  Soup,
} from "@lucide/vue";

export const icons = {
  actions: {
    add: CirclePlus,
    edit: Pencil,
    delete: Trash2,
    close: X,
    next: ChevronRight,
    previous: ChevronLeft,
    complete: CircleCheck,
  },

  common: {
    clock: Clock3,
    calories: Flame,
    date: CalendarDays,
    person: PersonStanding,
    warning: TriangleAlert,
    help: CircleHelp,
    insight: Lightbulb,
    health: Stethoscope,
    trend: TrendingUp,
  },

  navigation: {
    home: House,
    nutrition: Utensils,
    activity: SportShoe,
    sleep: Moon,
    recommendations: MessageCircleHeart,
    progress: ChartNoAxesCombined,
    logout: LogOut,
    expand: ChevronDown,
    menu: Menu,
  },

  activities: {
    walking: Footprints,
    running: SportShoe,
    cycling: Bike,
    swimming: Waves,
    strength: Dumbbell,
    yoga: Flower2,
    dance: Music2,
    hiking: Mountain,
    football: Goal,
    basketball: Volleyball,
    other: CircleDot,
  },

  nutrition: {
    breakfast: Coffee,
    lunch: Sandwich,
    dinner: Soup,
    snack: Cookie,
    calories: Flame,
    protein: BicepsFlexed,
    carbs: Wheat,
    fat: Droplet,
  },

  sleep: {
    lastDuration: MoonStar,
    averageDuration: Clock3,
    quality: CircleCheck,
  },

  goals: {
    nutrition: Utensils,
    activity: Dumbbell,
    sleep: MoonStar,
    weight: Scale,
    target: Goal,
  },
};
